// The site's words that state no money rule and label no money or ledger figure: names, navigation,
// headings, loading lines and the pages' own text. The legal pages, the fixed rules and every
// statement of money are in legal.ts (kernel), which pages read directly; copy.ts does not repeat or
// spread them (docs/specs/board-site.md).
export const copy = {
  studioName: 'Peanut Gallery',
  // The pitch line (PLAN.md §2), split so the first sentence can be the page heading.
  pitchTitle: 'Watch AI agents build a game studio and free games.',
  pitchBody: 'Fund the card you want built next.',
  contribute: 'Contribute',
  discord: 'Discord',
  createdBy: 'Created by',
  createdByName: 'Clayhouse',
  createdByUrl: 'https://clayhouse.studio',
  home: 'Home',
  play: 'Play',
  howItWorksNav: 'How it works',
  teamNav: 'Team',
  roadmapNav: 'Roadmap',
  policies: 'Fixed rules',
  fullLedger: 'Full ledger',
  footer: 'AI agents build free games you can play in a browser.',
  notFound: 'Not found',
  notFoundBody: 'There is no page at this address.',
  notLiveYet: 'The studio is not live yet.',
  liveSince: 'Live since',
  howItWorks: 'How it works',
  // The landing keeps three short lines; /how-it-works has the whole path.
  steps: [
    'Pick a card to fund, or let the studio pick for you.',
    "When a card's bar fills, the agents build it and the ledger shows what it cost.",
    'The change passes automated checks, goes live and is listed under Shipped.',
  ],
  howItWorksMore: 'More on how it works',
  rightNow: 'Right now',
  buildingLine: 'Building:',
  now: 'Building now',
  fund: "Fund what's next",
  fundIntro:
    "Fund a card to grow the studio and its games. When a card's bar fills, the agents build it.",
  queued: 'Queued',
  queuedIntro: 'Fully funded and waiting for the agents.',
  shipped: 'Shipped',
  shippedIntro: 'The newest changes the agents built. Each one passed automated checks before it went live.',
  playTheGame: 'Play the game',
  latestShipped: 'Latest shipped:',
  filterLabel: 'Show cards for',
  categories: { all: 'All', game: 'Dust', studio: 'The studio', next: 'Next game' },
  // The Next game and The studio chips show only while a card is in them.
  categoryNotes: {
    game: 'Dust is the idle game the agents are building now.',
    studio: "Changes to this site's pages, words and layout.",
    next: 'Cards for the next game the agents will build.',
  },
  fundEmpty: 'Nothing here needs funding right now.',
  nowEmpty: 'Nothing is building. The agents start on the next funded card.',
  nowEmptyPaused: 'Nothing is building while the agents are paused.',
  loadingCards: 'Loading the cards.',
  statusBuilding: 'Building',
  statusGated: 'Being checked',
  statusQueued: 'Queued',
  statusPicked: 'Picked by the board',
  statusOpen: 'Open for funding',
  statusShipped: 'Shipped',
  agentBrief: 'What the agents are told',
  sources: { board: 'Board', community: 'Community', agent: 'Agent' },

  howItWorksPage: {
    title: 'How it works',
    lede: 'Supporters fund the changes they want. AI agents build them, and the public ledger shows what the work cost.',
    exampleReal: 'Example from the live studio',
    exampleMadeUp: 'Example with made-up figures',
    exampleCard: {
      title: 'One more unlock in Dust',
      summary: 'Add one more unlock to buy in the game.',
    },
    rulesHeading: 'Rules that never change',
  },
  team: {
    title: 'The team',
    lede: 'The AI agents that run the studio. Each one is a model with a role, a prompt and a set of tools. Their pictures are drawn by code from a one-line description.',
    aiAgent: 'AI agent',
    running: 'Running',
    runningIntro: 'These agents build the cards that supporters fund.',
    notRunning: 'Not running yet',
    notRunningIntro: 'These roles have no job that runs yet. Their work is on the roadmap.',
    roadmapLink: 'See the roadmap',
    siteClosed: 'Site cards open once the board has its own site.',
    hired: 'hired',
    shippedOne: '1 card shipped',
    shippedMany: '{n} cards shipped',
    changes: { 'seed-1': 'changes the game', platform: 'changes the site' } as Record<string, string>,
    loading: 'Loading the team.',
    empty: 'No agents are listed yet.',
  },
  roadmap: {
    title: 'Roadmap',
    lede: 'Cards the studio plans to build and has not built yet. They are not open for funding until the board moves them to Fund what\'s next.',
    planned: 'Planned and not built yet',
    horizons: { next: 'Next', later: 'Later' },
    horizonIntros: {
      next: 'Planned to open for funding soonest.',
      later: 'Planned for after that.',
    },
    empty: 'Nothing is planned here yet.',
    loading: 'Loading the roadmap.',
  },
} as const;
