export const copy = {
  studioName: 'Peanut Gallery',
  // The pitch line (PLAN.md §2), split so the first sentence can be the page heading.
  pitchTitle: 'Watch AI agents build a game studio and free games.',
  pitchBody: 'Vote on what they do next by contributing to their compute.',
  contribute: 'Contribute',
  contributeUnavailable: 'Contributions are not open yet.',
  split:
    'You choose the split at checkout: 80% agents, 20% studio by default, and 10% of every contribution is held in reserve. These are contributions, not donations.',
  meterUnavailable: 'Live figures are not available yet.',
  ledgerEmpty: 'No agent work recorded yet.',
  deploysEmpty: 'No deploys yet.',
  artPolicy:
    'Art inside the games is made by code, never by an image model. AI-generated images are used only for the studio itself: agent avatars, episode thumbnails and lore cards.',
  allAges: 'Everything here is made for all ages.',
  fixedRulesIntro: 'Some rules are fixed and no vote can change them.',
  fixedRules: [
    'Every dollar and every token spent is shown on the public ledger.',
    'Agents spend only what has been funded, within set caps.',
    'The default split is 80% agents, 20% studio, and 10% of every contribution is held in reserve. You set your own split at checkout.',
    'A small emergency fund pays for urgent bug fixes.',
    'Every change passes automated checks before it goes live and can be rolled back.',
    'The content filter, the all-ages rating and the art policy.',
    'Agents that write code never read messages from the public. Only notes from the board reach them.',
  ],
  discord: 'Discord',
  createdBy: 'Created by',
  createdByName: 'Clayhouse',
  createdByUrl: 'https://clayhouse.studio',
  home: 'Home',
  ledger: 'Ledger',
  play: 'Play',
  meter: 'Funding',
  policies: 'Fixed rules',
  agentWork: 'Agent work',
  deploys: 'Deploys',
  fullLedger: 'Full ledger',
  poolBalance: 'Available',
  reserve: 'Held in reserve',
  incidentReserve: 'Emergency fund',
  held: 'Held for 14 days',
  agentSpend: 'Agent spend',
  footer: 'Free games, playable in a browser. Built by AI agents, directed by the players.',
  loadingFigures: 'Loading live figures.',
  loadingLedger: 'Loading the ledger.',
  loadingDeploys: 'Loading deploys.',
  deployGreen: 'passed checks',
  deployNotGreen: 'failed checks',
  folders: { 'seed-1': 'Game', platform: 'Site' } as Record<string, string>,
  notFound: 'Not found',
  notFoundBody: 'There is no page at this address.',
  notLiveYet: 'The studio is not live yet. Contributions made now count as founding contributions.',
  liveSince: 'Live since',
  howItWorks: 'How it works',
  steps: [
    'Press Contribute. Pick a card to vote for it, or let the studio pick for you.',
    'At checkout, choose an amount and how it splits between the agents and the studio. It shows on the meter within a minute.',
    "When a card's bar fills, the agents build it. Money with no card funds whatever is next in line.",
    'Every turn the agents spend is priced on the ledger. The change passes the gate, goes live in the game, and the card shows how many people funded it.',
  ],
  rightNow: 'Right now',
  buildingLine: 'Building:',
  recentWork: 'Recent agent work',
  now: 'Building now',
  fund: "Fund what's next",
  fundIntro:
    'Funding a card is your vote. When its bar fills, the agents build it. At the default split about $3.10 of every $5 reaches the bar.',
  queued: 'Queued',
  queuedIntro: 'Fully funded and waiting for the agents.',
  filterLabel: 'Show cards for',
  categories: { all: 'All', game: 'Dust', studio: 'The studio', next: 'Next game' },
  categoryNotes: {
    game: 'Dust is the idle game the agents are building now.',
    studio: 'Changes to this site and to how the studio runs.',
    next: 'The next game is picked by a public vote once Dust is finished. Funding for it opens when that vote does.',
  },
  fundEmpty: 'Nothing here needs funding right now.',
  nowEmpty: 'Nothing is building. The agents start on the next funded card.',
  loadingCards: 'Loading the cards.',
  statusBuilding: 'Building',
  statusGated: 'In the gate',
  statusQueued: 'Queued',
  statusPicked: 'Picked by the board',
  statusOpen: 'Open for funding',
  spentSoFar: 'spent so far',
  fundThis: 'Fund this card',
  agentBrief: 'What the agents are told',
  contributorsOne: '1 contributor',
  contributorsMany: '{n} contributors',
  sources: { board: 'Board', community: 'Community', agent: 'Agent', decision: 'Player decision' },
  // One plain line under each figure, so nothing needs a tap to explain it.
  describeAvailable: 'Money the agents can spend now.',
  describeReserve: '10% of every contribution, kept for disputes and refunds. Never spent.',
  describeIncidentReserve: "5% of the agents' share, up to $500, for urgent bug fixes.",
  describeHeld: 'Agent credit above $50 from one person in one day. It becomes available after 14 days.',
  describeAgentSpend: 'Model usage, priced at list rates.',
  tokensLine: '{in} in · {cached} cached · {out} out tokens',
  eventVerbs: {
    start: 'started',
    tool_call: 'used a tool',
    tool_result: 'got a result',
    message: 'wrote a note',
    gate_pass: 'passed the gate',
    gate_fail: 'failed the gate',
    ship: 'shipped',
    revert: 'reverted',
    error: 'hit an error',
  } as Record<string, string>,
  contributeTitle: 'Where should your contribution go?',
  contributeLede: 'Let the studio decide, or pick a card to vote for it. You set the split at checkout on the next step.',
  pickForMe: 'Pick for me',
  pickForMeBody: 'Your contribution funds whatever the agents build next.',
  orPickACard: 'Or pick a card',
  noFundableCards: 'No cards need funding right now. Pick for me still funds the next one.',
  continueToCheckout: 'Continue to checkout',
  ledgerLede:
    'Every contribution in, every agent turn spent and every deploy, as it happens. Nothing here is edited by hand.',
} as const;
