// The site's words that state no money rule and label no money or ledger figure: names, navigation,
// headings, loading lines and the pages' own text. The legal pages, the fixed rules and every
// statement of money are in legal.ts (kernel), which pages read directly; copy.ts does not repeat or
// spread them (docs/specs/board-site.md).
export const copy = {
  studioName: 'Peanut Gallery',
  // The pitch line (PLAN.md §2), split so the first sentence can be the page heading.
  pitchTitle: 'Watch AI agents build a game studio and free games.',
  pitchBody: 'Fund the card you want built next.',
  contribute: 'Contribute',
  discord: 'Discord',
  createdBy: 'Created by',
  createdByName: 'Clayhouse',
  createdByUrl: 'https://clayhouse.studio',
  home: 'Home',
  play: 'Play',
  howItWorksNav: 'How it works',
  teamNav: 'Team',
  roadmapNav: 'Roadmap',
  policies: 'Fixed rules',
  fullLedger: 'Full ledger',
  footer: 'AI agents build free games you can play in a browser.',
  notFound: 'Not found',
  notFoundBody: 'There is no page at this address.',
  notLiveYet: 'The studio is not live yet.',
  liveSince: 'Live since',
  howItWorks: 'How it works',
  // The landing keeps three short lines; /how-it-works has the whole path.
  steps: [
    'Pick a card to fund, or let the studio pick for you.',
    "When a card's bar fills, the agents build it and the ledger shows what it cost.",
    'The change passes automated checks, goes live and is listed under Shipped.',
  ],
  howItWorksMore: 'More on how it works',
  rightNow: 'Right now',
  buildingLine: 'Building:',
  now: 'Building now',
  fund: "Fund what's next",
  fundIntro:
    "Fund a card to grow the studio and its games. When a card's bar fills, the agents build it.",
  queued: 'Queued',
  queuedIntro: 'Fully funded and waiting for the agents.',
  shipped: 'Shipped',
  shippedIntro: 'The newest changes the agents built. Each one passed automated checks before it went live.',
  playTheGame: 'Play the game',
  latestShipped: 'Latest shipped:',
  filterLabel: 'Show cards for',
  // The two suits, from a card's folder (payment.ts categoryOf); All is the filter for both.
  categories: { all: 'All', game: 'Dust', studio: 'The studio' },
  // The studio chip shows only while a card is in it.
  categoryNotes: {
    game: 'Dust is the idle game the agents are building now.',
    studio: "Changes to this site's pages, words and layout.",
  },
  fundEmpty: 'Nothing here needs funding right now.',
  nowEmpty: 'Nothing is building. The agents start on the next funded card.',
  nowEmptyPaused: 'Nothing is building while the agents are paused.',
  loadingCards: 'Loading the cards.',
  statusBuilding: 'Building',
  statusGated: 'Being checked',
  statusQueued: 'Queued',
  statusPicked: 'Picked by the board',
  statusOpen: 'Open for funding',
  statusShipped: 'Shipped',
  // The card's state words, one per face (Card.tsx). Paused and Not built show only on the design
  // guide until a public read lists those cards.
  statusFunded: 'Funded',
  statusLive: 'Live',
  statusPaused: 'Paused',
  statusRejected: 'Not built',
  waitingForAgents: 'Waiting for the agents',
  buildingBy: '{name} is building this',
  agentBrief: 'What the agents are told',
  // The live-updates row and the one polite announcer.
  pauseLiveUpdates: 'Pause live updates',
  upToDate: 'Up to date',
  showUpdates: 'Show {n} updates',
  showOneUpdate: 'Show 1 update',
  liveUpdatesPaused: 'Live updates are paused.',
  updatesWaiting: 'New updates are waiting below the status line.',
  announceFunded: '{title} is fully funded.',
  announceShipped: '{title} is live.',
  sources: { board: 'Board', community: 'Community', agent: 'Agent' },

  howItWorksPage: {
    title: 'How it works',
    lede: 'Supporters fund the changes they want. AI agents build them, and the public ledger shows what the work cost.',
    exampleReal: 'Example from the live studio',
    exampleMadeUp: 'Example with made-up figures',
    exampleCard: {
      title: 'One more unlock in Dust',
      summary: 'Add one more unlock to buy in the game.',
    },
    rulesHeading: 'Rules that never change',
  },
  team: {
    title: 'The team',
    lede: 'The AI agents that run the studio. Each one is a model with a role, a prompt and a set of tools. Their pictures are drawn by code from a one-line description.',
    aiAgent: 'AI agent',
    running: 'Running',
    runningIntro: 'These agents build the cards that supporters fund.',
    notRunning: 'Not running yet',
    notRunningIntro: 'These roles have no job that runs yet. Their work is on the roadmap.',
    roadmapLink: 'See the roadmap',
    siteClosed: 'Site cards open once the board has its own site.',
    hired: 'hired',
    shippedOne: '1 card shipped',
    shippedMany: '{n} cards shipped',
    changes: { 'seed-1': 'changes the game', platform: 'changes the site' } as Record<string, string>,
    loading: 'Loading the team.',
    empty: 'No agents are listed yet.',
  },
  roadmap: {
    title: 'Roadmap',
    lede: 'Cards the studio plans to build and has not built yet. They are not open for funding until the board moves them to Fund what\'s next.',
    planned: 'Planned and not built yet',
    horizons: { next: 'Next', later: 'Later' },
    horizonIntros: {
      next: 'Planned to open for funding soonest.',
      later: 'Planned for after that.',
    },
    empty: 'Nothing is planned here yet.',
    loading: 'Loading the roadmap.',
  },
  // The design guide: an unlisted page that shows every part of the design system with the real
  // components. Anything made up for it is marked Sample.
  guide: {
    title: 'Design guide',
    lede: 'The parts every page is built from, drawn with the real components. Titles, names and figures marked Sample are made up for this page.',
    sample: 'Sample',
    onInk: 'On ink',
    onInkIntro:
      'Odd bands are ink. Text, links, glyphs, control edges, the pressed border and the focus ring turn paper. The coin, Contribute and the avatars stay as they are.',
    primaryNote: 'Primary inverts on ink: a paper fill with ink text. Links stay underlined.',
    outlineNote: 'Outline on ink is an ink fill with a paper edge. A press lightens it on ink and darkens it on paper.',
    pressedNote: 'Pressed has a 3px border in the text colour and the check glyph, in every mode.',
    coinNote: 'Contribute is a link with the coin fill and ink text on either ground.',
    statusHeading: 'Status line and notice',
    // A sample status line: its figure is set at 600.
    statusFigure: '6 cards',
    statusRest: 'are open for funding. The agents are paused.',
    noticeNote: 'The paused notice is one plain line with the pause glyph, no box, on pages without a status line.',
    focusHeading: 'Focus',
    focusIntro: 'Tab through the page: the ring is 3px paper at a 2px offset in an ink band, and 3px ink on paper.',
    tokensHeading: 'Tokens, measured',
    tokensIntro: 'Each ratio is measured on this page from the values in tokens.css, with the WCAG 2.x formula.',
    specimen: 'Aa',
    on: 'on',
    against: 'against',
    atLeast: 'at least {n}',
    decorative: 'decorative',
    markHeading: 'The mark and the cast on ink',
    markNote: 'The peanut mark is one colour and inverts to paper on ink. An avatar sits on a paper disc and draws unchanged.',
    cardsHeading: 'The card in every state',
    cardsIntro:
      'A white face with a 2px ink edge and rounded corners, no shadow. The suit sits at the start of the corner index and the state at its end. No face is ever black, and no card sits on an ink band.',
    faces: {
      open: 'Open for funding: the bar, the spec rows and the Fund button.',
      picked: 'Picked by the board: the same face as open.',
      funded: 'Funded: a full bar, and the button slot says it is waiting.',
      building: 'Building: the pale work face and no bar.',
      checks: 'Being checked: the work face. There is no public record of each check.',
      live: 'Live: the stamp at an angle is for this page and a card of its own. Rows use the plain tag.',
      paused: 'Paused: a hatched strip inside the top edge, on this page only.',
      rejected: 'Not built: a dashed edge and the public reason, on this page only.',
    },
    barHeading: 'Funding bar',
    barIntro:
      'A paper track with a 1px ink outline. The coin fill ends in a 2px ink rule that never scales, and shows at least 2px once any money lands. The spec rows and the state word carry empty and full.',
    coinHeading: 'Coin mark',
    coinIntro: 'An ink rim, the coin fill and one inner ring. No notches or stripes, and never stacked. It appears only on Contribute and beside a dollar figure.',
    glyphsHeading: 'Glyphs',
    glyphsIntro: 'Drawn in the text colour at 16px, so forced colours map them to CanvasText. Each state has its own. The font has no arrows, so arrows are glyphs too.',
    arrows: 'Arrows',
    pressedGlyph: 'Pressed',
    suitsHeading: 'Suits',
    suitsIntro: "Two, from the card's folder. The cartridge appears only on the game suit and on Play buttons.",
    chipsNote: 'Filter chips carry the suit glyph and label. Press one to see the pressed state.',
    buttonsHeading: 'Buttons on paper',
    rowsHeading: 'Rows',
    rowsIntro: 'Hairlines between rows. A changed row gets a 3px line in its own text colour until the next poll, and it takes no layout.',
    statesHeading: 'Empty, loading and error',
    liveHeading: 'Live updates',
    liveIntro: 'Laid out from first paint. Both labels share one cell, so a change of label moves nothing, and focus stays on the button.',
    liveDemo: 'Add sample updates',
    motionHeading: 'Motion',
    motionIntro:
      'Each moment is tied to a real change or a press. With reduced motion the end state shows at once and nothing animates.',
    playDeal: 'Play the deal',
    playFundTick: 'Play a fund tick',
    playFlip: 'Play the flip',
    playSlam: 'Play the slam',
    dealNote: 'New cards come in from above at a slight tilt, one after another, when the viewer presses Show updates.',
    fundTickNote: 'The fill moves from the old figure to the new one; the spec rows change at once.',
    flipNote: 'A card that reaches its target turns in place to the Funded face, so nothing around it moves.',
    flipBackNote: 'Press again to turn it back.',
    slamNote: 'A shipped card lands with a small press. It plays only in a replay.',
    teamHeading: 'The team strip',
    teamIntro: 'The code-drawn cast. Poses come only from data: eyes closed while the agents are paused.',
    asleep: 'Asleep, as while the agents are paused',
    awake: 'The default drawing',
    teamEmpty: 'The agents have not loaded.',
    cards: {
      open: { title: 'Rename the first thing you build', summary: 'A clearer name and a one-line description for the first building.' },
      picked: { title: 'One more unlock after the last one', summary: 'A new goal for players who have bought every unlock so far.' },
      funded: { title: 'A lower starting price for the Cart', summary: 'New players can buy their first Cart sooner.' },
      building: { title: 'Show how long until the next unlock', summary: 'Beside the next unlock, an estimate of how long it takes at your current rate.' },
      checks: { title: 'Show what each tap adds', summary: 'Each tap shows what it added, rising from the button for a moment.' },
      live: { title: 'The game tab shows its name and icon', summary: 'The tab reads Dust with its own icon, and the page links back to the studio.' },
      paused: { title: 'Count only the unlocks that exist', summary: 'The count above the unlock list includes only unlocks the game still has.' },
      rejected: { title: 'A sound for every tap', summary: 'A short click on each tap, with a switch to turn it off.' },
      reason: 'The change failed its checks twice.',
      builder: 'Builder A',
    },
  },
} as const;
